### ISSUE TITLE
consoletype.c doesn't compile on Solaris

### ISSUE THREAD

**Issue by grobian** [gentoo/gentoo-functions#3]
>>> Compiling source in /gentoo/prefix64/var/tmp/portage/sys-apps/gentoo-functions-9999/work/gentoo-functions-9999 ...
make -j3 
x86_64-pc-solaris2.11-gcc -O3 -Wall    consoletype.c   -o consoletype
consoletype.c: In function ‘main’:
consoletype.c:25:2: warning: implicit declaration of function ‘major’ [-Wimplicit-function-declaration]
consoletype.c:19:16: warning: unused variable ‘twelve’ [-Wunused-variable]
/gentoo/prefix64/var/tmp/portage/sys-apps/gentoo-functions-9999/temp/ccV8aGl3.o: In function `main':
consoletype.c:(.text.startup+0x25): undefined reference to `major'
collect2: error: ld returned 1 exit status
<builtin>: recipe for target 'consoletype' failed
make: *** [consoletype] Error 1
 * ERROR: sys-apps/gentoo-functions-9999::x-gentoo-x86 failed (compile phase):

major doesn't exist on Solaris.

I found ftp://distro.ibiblio.org/pub/linux/distributions/rootlinux/rootlinux-ports/base/kbd/consoletype.c which feels like a better approach, but since I needed to have something working I used a simple shell script to do roughly the same http://dev.gentoo.org/~grobian/distfiles/consoletype-1.0.sh

**Comment by williamh** [comment]
Interestingly the code you point to is also Gentoo code, so I'll look at getting it into the code base; I don't know why this code wasn't part of bl1, which is where I got the original code.

**Comment by grobian** [comment]
>>> Compiling source in /gentoo/prefix64/var/tmp/portage/sys-apps/gentoo-functions-9999/work/gentoo-functions-9999 ...
make -j3 
x86_64-pc-solaris2.11-gcc -O3 -Wall -pipe    consoletype.c   -o consoletype
>>> Source compiled.

and it seems to work for the pty at least.
